#!/bin/bash

NUMBER_ITERATIONS="20"
NUMBER_COLORS="100"
NUMBER_SUPERPIXELS="600"
DATASET_NAME="MSRA10K"

for file in ../datasets/"$DATASET_NAME"/images/*
do
  ./iftIFCS "${file##*/}" "$NUMBER_ITERATIONS" "$DATASET_NAME" "$NUMBER_COLORS" "$NUMBER_SUPERPIXELS"
done
