name: mo445
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - scipy
  - matplotlib
  - jupyter
  - notebook
  - pandas
  - scikit-image
  - scikit-learn
  - opencv
  - pillow
  - seaborn
  - ipywidgets
  - pip
  - pip:
    - pyift
