#!/bin/sh
set -x #echo on
set -e #stop on errors

if [ -z $NEWIFT_DIR ]; then
  echo "Error -- Requires the $$NEWIFT_DIR environment variable set to base IFT folder."
  exit 1
fi

if [ -z $1 ]; then
  echo "Usage $0 <datasets_folder>"
  exit 1
fi

FIG_SCRIPT=$NEWIFT_DIR/demo/ImageActiveLearning/scripts/PRL_Figures.sh
BASE_DIR=$1

CSV_NAME="full_sp_metrics.csv"

RISF_PATH=RISF_1.5/PATHCOST_1_ALPHA_0.5/
RISF_NAME="RISF"
GEO_PATH=RISF_SIBGRAPI/SAMPLING_4_PATHCOST_2_ALPHA_0.5/
#GEO_PATH=RISF_SIBGRAPI_TRUE/
GEO_NAME="RISF-geo*"
ISF_PATH=FastISF/PATHCOST_0_ALPHA_0.5/
ISF_NAME="ISF"
PRG_PATH=PRG_RISF15_sp/
PRG_NAME="RISF-merge"
PRB_PATH=PRG_BIG_sp/
PRB_NAME="BigRISF-merge"
PRH_PATH=PRG_SH_sp/
PRH_NAME="SH-merge"
UCM_PATH=UCM_sp/
UCM_NAME="gPb-owt-UCM"
FAST_PATH=UCM_FAST_borders_sp/
FAST_NAME="MCG-fast"
ACC_PATH=UCM_ACC_borders_sp/
ACC_NAME="MCG-acc"
SH_PATH=SH_MST_sp/
SH_NAME="SH"
ERS_PATH=ERS_sp/
ERS_NAME="ERS"
LSC_PATH=LSC/
LSC_NAME="LSC"
ERGC_PATH=ERGC/
ERGC_NAME="ERGC"
SLIC_PATH=SLIC/
SLIC_NAME="SLIC"

BERK_PATH=$BASE_DIR/berkeley500_test/
$FIG_SCRIPT $BERK_PATH spl_berk \
  $BERK_PATH/$RISF_PATH/$CSV_NAME $RISF_NAME \
  $BERK_PATH/$PRG_PATH/$CSV_NAME $PRG_NAME \
  $BERK_PATH/$ISF_PATH/$CSV_NAME $ISF_NAME \
  $BERK_PATH/$SH_PATH/$CSV_NAME $SH_NAME \
  $BERK_PATH/$ERS_PATH/$CSV_NAME $ERS_NAME \
  $BERK_PATH/$LSC_PATH/$CSV_NAME $LSC_NAME \
  $BERK_PATH/$ERGC_PATH/$CSV_NAME $ERGC_NAME \
  $BERK_PATH/$SLIC_PATH/$CSV_NAME $SLIC_NAME \
  $BERK_PATH/$FAST_PATH/$CSV_NAME $FAST_NAME
 # $BERK_PATH/$GEO_PATH/$CSV_NAME $GEO_NAME \

MSRC_PATH=$BASE_DIR/MSRC/
$FIG_SCRIPT $MSRC_PATH spl_msrc \
  $MSRC_PATH/$RISF_PATH/$CSV_NAME $RISF_NAME \
  $MSRC_PATH/$PRG_PATH/$CSV_NAME $PRG_NAME \
  $MSRC_PATH/$ISF_PATH/$CSV_NAME $ISF_NAME \
  $MSRC_PATH/$SH_PATH/$CSV_NAME $SH_NAME \
  $MSRC_PATH/$ERS_PATH/$CSV_NAME $ERS_NAME \
  $MSRC_PATH/$LSC_PATH/$CSV_NAME $LSC_NAME \
  $MSRC_PATH/$ERGC_PATH/$CSV_NAME $ERGC_NAME \
  $MSRC_PATH/$SLIC_PATH/$CSV_NAME $SLIC_NAME \
  $MSRC_PATH/$FAST_PATH/$CSV_NAME $FAST_NAME
#  $MSRC_PATH/$GEO_PATH/$CSV_NAME $GEO_NAME \

BIRDS_PATH=$BASE_DIR/birds2/
$FIG_SCRIPT $BIRDS_PATH spl_birds \
  $BIRDS_PATH/$RISF_PATH/$CSV_NAME $RISF_NAME \
  $BIRDS_PATH/$PRG_PATH/$CSV_NAME $PRG_NAME \
  $BIRDS_PATH/$ISF_PATH/$CSV_NAME $ISF_NAME \
  $BIRDS_PATH/$SH_PATH/$CSV_NAME $SH_NAME \
  $BIRDS_PATH/$ERS_PATH/$CSV_NAME $ERS_NAME \
  $BIRDS_PATH/$LSC_PATH/$CSV_NAME $LSC_NAME \
  $BIRDS_PATH/$ERGC_PATH/$CSV_NAME $ERGC_NAME \
  $BIRDS_PATH/$SLIC_PATH/$CSV_NAME $SLIC_NAME \
  $BIRDS_PATH/$FAST_PATH/$CSV_NAME $FAST_NAME
#  $BIRDS_PATH/$GEO_PATH/$CSV_NAME $GEO_NAME \

LIVER_PATH=$BASE_DIR/LiverCT/
$FIG_SCRIPT $LIVER_PATH spl_liver \
  $LIVER_PATH/$RISF_PATH/$CSV_NAME $RISF_NAME \
  $LIVER_PATH/$PRG_PATH/$CSV_NAME $PRG_NAME \
  $LIVER_PATH/$GEO_PATH/$CSV_NAME $GEO_NAME \
  $LIVER_PATH/$ISF_PATH/$CSV_NAME $ISF_NAME \
  $LIVER_PATH/$SH_PATH/$CSV_NAME $SH_NAME \
  $LIVER_PATH/$ERS_PATH/$CSV_NAME $ERS_NAME \
  $LIVER_PATH/$LSC_PATH/$CSV_NAME $LSC_NAME \
  $LIVER_PATH/$ERGC_PATH/$CSV_NAME $ERGC_NAME \
  $LIVER_PATH/$SLIC_PATH/$CSV_NAME $SLIC_NAME
  #$LIVER_PATH/$PRH_PATH/$CSV_NAME $PRH_NAME

