#!/bin/sh
set -x #echo on
set -e #stop on errors

EXEC_PY="python py_scripts/SuperpixelPlot.py"

FISF_NSP_COL=2
FISF_TIME_COL=0
FISF_BR_COL=`expr ${FISF_NSP_COL} + 2`
FISF_UBR_COL=`expr ${FISF_NSP_COL} + 4`
FISF_BP_COL=`expr ${FISF_NSP_COL} + 6`
FISF_UBP_COL=`expr ${FISF_NSP_COL} + 8`
FISF_BF_COL=`expr ${FISF_NSP_COL} + 10`
FISF_UBF_COL=`expr ${FISF_NSP_COL} + 12`
FISF_ASA_COL=`expr ${FISF_NSP_COL} + 14`
FISF_UE_COL=`expr ${FISF_NSP_COL} + 16`
FISF_COMP_COL=`expr ${FISF_NSP_COL} + 18`
FISF_DICE_COL=`expr ${FISF_NSP_COL} + 22`

RISF_NSP_COL=10
RISF_TIME_COL=8
RISF_BR_COL=`expr ${RISF_NSP_COL} + 2`
RISF_UBR_COL=`expr ${RISF_NSP_COL} + 4`
RISF_BP_COL=`expr ${RISF_NSP_COL} + 6`
RISF_UBP_COL=`expr ${RISF_NSP_COL} + 8`
RISF_BF_COL=`expr ${RISF_NSP_COL} + 10`
RISF_UBF_COL=`expr ${RISF_NSP_COL} + 12`
RISF_ASA_COL=`expr ${RISF_NSP_COL} + 14`
RISF_UE_COL=`expr ${RISF_NSP_COL} + 16`
RISF_COMP_COL=`expr ${RISF_NSP_COL} + 18`
RISF_DICE_COL=`expr ${RISF_NSP_COL} + 22`
RISF_FULLTIME_COL=`expr ${RISF_NSP_COL} + 25`
BRAIN_RISF_FULLTIME_COL=`expr ${RISF_NSP_COL} + 31`

# General names for axis labels
NSP_NAME="Number of superpixels"
TIME_NAME="Time (ms)"
BR_NAME="Boundary Recall"
UBR_NAME="Groundtruth Union Boundary Recall"
BP_NAME="Boundary Precision"
UBP_NAME="Groundtruth Union Boundary Precision"
BF_NAME="Boundary F-Score"
UBF_NAME="Groundtruth Union Boundary F-Score"
ASA_NAME="Achievable Segmentation Accuracy (ASA)"
UE_NAME="Undersegmentation Error"
COMP_NAME="Compactness"
DICE_NAME="Dice"
DICEAVG_NAME="Average Dice"

# Brain Plots
BRAIN_BASE=resultPack/Brain
BRAIN_NSP_RANGE="500 10000 0"
BRAIN_TIME_RANGE="0 50000 0"
BRAIN_BR_RANGE="0.9 1.00 0" 
BRAIN_UE_RANGE="0.01 0.07 0" 
BRAIN_DICE_RANGE="0.80 0.96 0"
BRAIN_DICEOBJ1_RANGE="0.75 0.96 0"
BRAIN_DICEOBJ2_RANGE="0.85 0.97 0"
BRAIN_DICEOBJ3_RANGE="0.85 0.97 0"
BRAIN_NUM_METHODS=3
BRAIN_METHOD1="${BRAIN_BASE}/BRAIN_QQ_FISF_4096_results.csv ISF-GRID-MEAN 0 1"
BRAIN_METHOD2="${BRAIN_BASE}/BRRRAIN_GRID_results.csv RISF-GRID 5 2"
BRAIN_METHOD3="${BRAIN_BASE}/BRAIN_ISF_L0_25k_RISF_GEO_results.csv RISF-GEODESIC 2 0"

# Brain obj names
BRAIN_DICEOBJ1_NAME="Cerebelum Dice"
BRAIN_DICEOBJ2_NAME="Hemisphere 1 Dice"
BRAIN_DICEOBJ3_NAME="Hemisphere 2 Dice"

${EXEC_PY} ${BRAIN_BASE}/SIBGRAPI_TimePlot.pdf "${NSP_NAME}" ${BRAIN_NSP_RANGE} "${TIME_NAME}" ${BRAIN_TIME_RANGE} ${BRAIN_NUM_METHODS} ${BRAIN_METHOD1} ${FISF_NSP_COL} ${FISF_TIME_COL} ${BRAIN_METHOD2} ${RISF_NSP_COL} ${BRAIN_RISF_FULLTIME_COL} ${BRAIN_METHOD3} ${RISF_NSP_COL} ${BRAIN_RISF_FULLTIME_COL}
${EXEC_PY} ${BRAIN_BASE}/SIBGRAPI_brPlot.pdf "${NSP_NAME}" ${BRAIN_NSP_RANGE} "${BR_NAME}" ${BRAIN_BR_RANGE} ${BRAIN_NUM_METHODS} ${BRAIN_METHOD1} ${FISF_NSP_COL} ${FISF_BR_COL} ${BRAIN_METHOD2} ${RISF_NSP_COL} ${RISF_BR_COL} ${BRAIN_METHOD3} ${RISF_NSP_COL} ${RISF_BR_COL}
${EXEC_PY} ${BRAIN_BASE}/SIBGRAPI_uePlot.pdf "${NSP_NAME}" ${BRAIN_NSP_RANGE} "${UE_NAME}" ${BRAIN_UE_RANGE} ${BRAIN_NUM_METHODS} ${BRAIN_METHOD1} ${FISF_NSP_COL} ${FISF_UE_COL} ${BRAIN_METHOD2} ${RISF_NSP_COL} ${RISF_UE_COL} ${BRAIN_METHOD3} ${RISF_NSP_COL} ${RISF_UE_COL}
${EXEC_PY} ${BRAIN_BASE}/SIBGRAPI_DiceAvgPlot.pdf "${NSP_NAME}" ${BRAIN_NSP_RANGE} "${DICEAVG_NAME}" ${BRAIN_DICE_RANGE} ${BRAIN_NUM_METHODS} ${BRAIN_METHOD1} ${FISF_NSP_COL} ${FISF_DICE_COL} ${BRAIN_METHOD2} ${RISF_NSP_COL} ${RISF_DICE_COL} ${BRAIN_METHOD3} ${RISF_NSP_COL} ${RISF_DICE_COL}
${EXEC_PY} ${BRAIN_BASE}/SIBGRAPI_DiceObj1Plot.pdf "${NSP_NAME}" ${BRAIN_NSP_RANGE} "${BRAIN_DICEOBJ1_NAME}" ${BRAIN_DICEOBJ1_RANGE} ${BRAIN_NUM_METHODS} ${BRAIN_METHOD1} ${FISF_NSP_COL} `expr ${FISF_DICE_COL} + 2` ${BRAIN_METHOD2} ${RISF_NSP_COL} `expr ${RISF_DICE_COL} + 2` ${BRAIN_METHOD3} ${RISF_NSP_COL} `expr ${RISF_DICE_COL} + 2`
${EXEC_PY} ${BRAIN_BASE}/SIBGRAPI_DiceObj2Plot.pdf "${NSP_NAME}" ${BRAIN_NSP_RANGE}  "${BRAIN_DICEOBJ2_NAME}" ${BRAIN_DICEOBJ2_RANGE} ${BRAIN_NUM_METHODS} ${BRAIN_METHOD1} ${FISF_NSP_COL} `expr ${FISF_DICE_COL} + 4` ${BRAIN_METHOD2} ${RISF_NSP_COL} `expr ${RISF_DICE_COL} + 4` ${BRAIN_METHOD2} ${RISF_NSP_COL} `expr ${RISF_DICE_COL} + 4` ${BRAIN_METHOD3} ${RISF_NSP_COL} `expr ${RISF_DICE_COL} + 4`
${EXEC_PY} ${BRAIN_BASE}/SIBGRAPI_DiceObj3Plot.pdf "${NSP_NAME}" ${BRAIN_NSP_RANGE} "${BRAIN_DICEOBJ3_NAME}" ${BRAIN_DICEOBJ3_RANGE} ${BRAIN_NUM_METHODS} ${BRAIN_METHOD1} ${FISF_NSP_COL} `expr ${FISF_DICE_COL} + 6` ${BRAIN_METHOD2} ${RISF_NSP_COL} `expr ${RISF_DICE_COL} + 6` ${BRAIN_METHOD3} ${RISF_NSP_COL} `expr ${RISF_DICE_COL} + 6`
${EXEC_PY} ${BRAIN_BASE}/SIBGRAPI_DiceAvgxTimePlot.pdf "${DICEAVG_NAME}" ${BRAIN_DICE_RANGE} "${TIME_NAME}" ${BRAIN_TIME_RANGE} ${BRAIN_NUM_METHODS} ${BRAIN_METHOD1} ${FISF_DICE_COL} ${FISF_TIME_COL} ${BRAIN_METHOD2} ${RISF_DICE_COL} ${BRAIN_RISF_FULLTIME_COL} ${BRAIN_METHOD3} ${RISF_DICE_COL} ${BRAIN_RISF_FULLTIME_COL}

# Berk Plots
BERK_BASE=resultPack/Berk
BERK_NSP_RANGE="50 500 0"
BERK_TIME_RANGE="0 300 0"
BERK_BR_RANGE="0.6 0.95 0" 
BERK_UBR_RANGE="0.6 0.95 0" 
BERK_BP_RANGE="0.1 0.3 0"
BERK_UBP_RANGE="0.25 0.5 0"
BERK_BF_RANGE="0.2 0.4 0"
BERK_UBF_RANGE="0.38 0.53 0"
BERK_ASA_RANGE="0.87 0.97 0"
BERK_UE_RANGE="0.05 0.28 0"
BERK_COMP_RANGE="0 0.5 0"

# Berk ISF vs RISF comparison
BERK_ISF_NUM_METHODS=4
BERK_ISF1="${BERK_BASE}/FISF_GRID_results.csv ISF-GRID-MEAN 0 1"
BERK_ISF2="${BERK_BASE}/FISF_MIX_results.csv ISF-MIX-MEAN 1 3"
BERK_ISF3="${BERK_BASE}/FISF_L0_MEAN_10k_012_L1_GRID_05_results.csv RISF-GRID 5 2"
BERK_ISF4="${BERK_BASE}/FISF_L0_MEAN_10k_012_L1_GEO_results.csv RISF-GEODESIC 2 0"

${EXEC_PY} ${BERK_BASE}/SIBGRAPI_br_plot.pdf "${NSP_NAME}" ${BERK_NSP_RANGE} "${BR_NAME}" ${BERK_BR_RANGE} ${BERK_ISF_NUM_METHODS} ${BERK_ISF1} ${FISF_NSP_COL} ${FISF_BR_COL} ${BERK_ISF2} ${FISF_NSP_COL} ${FISF_BR_COL} ${BERK_ISF3} ${RISF_NSP_COL} ${RISF_BR_COL} ${BERK_ISF4} ${RISF_NSP_COL} ${RISF_BR_COL}
${EXEC_PY} ${BERK_BASE}/SIBGRAPI_ue_plot.pdf "${NSP_NAME}" ${BERK_NSP_RANGE} "${UE_NAME}" ${BERK_UE_RANGE} ${BERK_ISF_NUM_METHODS} ${BERK_ISF1} ${FISF_NSP_COL} ${FISF_UE_COL} ${BERK_ISF2} ${FISF_NSP_COL} ${FISF_UE_COL} ${BERK_ISF3} ${RISF_NSP_COL} ${RISF_UE_COL} ${BERK_ISF4} ${RISF_NSP_COL} ${RISF_UE_COL}
${EXEC_PY} ${BERK_BASE}/SIBGRAPI_time_plot.pdf "${NSP_NAME}" ${BERK_NSP_RANGE} "${TIME_NAME}" ${BERK_TIME_RANGE} ${BERK_ISF_NUM_METHODS} ${BERK_ISF1} ${FISF_NSP_COL} ${FISF_TIME_COL} ${BERK_ISF2} ${FISF_NSP_COL} ${FISF_TIME_COL} ${BERK_ISF3} ${RISF_NSP_COL} ${RISF_FULLTIME_COL} ${BERK_ISF4} ${RISF_NSP_COL} ${RISF_FULLTIME_COL}

# Liver Plots
LIVER_BASE=resultPack/Liver
LIVER_NSP_RANGE="50 500 0"
LIVER_TIME_RANGE="0 500 0"
LIVER_BR_RANGE="0.69 1.00 0" 
LIVER_UE_RANGE="0.00 0.06 0"
LIVER_COMP_RANGE="0 0.6 0"
LIVER_ASA_RANGE="0.97 1.0 0"
LIVER_DICE_RANGE="0.92 0.99 0"
LIVER_NUM_METHODS=4
LIVER_METHOD1="${LIVER_BASE}/LIVER_QQ_FISF_GRID_32_results.csv ISF-GRID-MEAN 0 1"
LIVER_METHOD2="${LIVER_BASE}/LIVER_FISF_MIX_ALPHA_128_results.csv ISF-MIX-MEAN 1 3"
LIVER_METHOD3="${LIVER_BASE}/RIBA_GRID_results.csv RISF-GRID 5 2"
LIVER_METHOD4="${LIVER_BASE}/L0_10000_32_L1_GEO_32_results.csv RISF-GEODESIC 2 0"

${EXEC_PY} ${LIVER_BASE}/SIBGRAPI_time_plot.pdf "${NSP_NAME}" ${LIVER_NSP_RANGE} "${TIME_NAME}" ${LIVER_TIME_RANGE} ${LIVER_NUM_METHODS} ${LIVER_METHOD1} ${FISF_NSP_COL} ${FISF_TIME_COL} ${LIVER_METHOD2} ${FISF_NSP_COL} ${FISF_TIME_COL} ${LIVER_METHOD3} ${RISF_NSP_COL} ${RISF_FULLTIME_COL} ${LIVER_METHOD4} ${RISF_NSP_COL} ${RISF_FULLTIME_COL}
${EXEC_PY} ${LIVER_BASE}/SIBGRAPI_br_plot.pdf "${NSP_NAME}" ${LIVER_NSP_RANGE} "${BR_NAME}" ${LIVER_BR_RANGE} ${LIVER_NUM_METHODS} ${LIVER_METHOD1} ${FISF_NSP_COL} ${FISF_BR_COL} ${LIVER_METHOD2} ${FISF_NSP_COL} ${FISF_BR_COL} ${LIVER_METHOD3} ${RISF_NSP_COL} ${RISF_BR_COL} ${LIVER_METHOD4} ${RISF_NSP_COL} ${RISF_BR_COL}
${EXEC_PY} ${LIVER_BASE}/SIBGRAPI_ue_plot.pdf "${NSP_NAME}" ${LIVER_NSP_RANGE} "${UE_NAME}" ${LIVER_UE_RANGE} ${LIVER_NUM_METHODS} ${LIVER_METHOD1} ${FISF_NSP_COL} ${FISF_UE_COL} ${LIVER_METHOD2} ${FISF_NSP_COL} ${FISF_UE_COL} ${LIVER_METHOD3} ${RISF_NSP_COL} ${RISF_UE_COL} ${LIVER_METHOD4} ${RISF_NSP_COL} ${RISF_UE_COL}
${EXEC_PY} ${LIVER_BASE}/SIBGRAPI_dice_plot.pdf "${NSP_NAME}" ${LIVER_NSP_RANGE} "${DICE_NAME}" ${LIVER_DICE_RANGE} ${LIVER_NUM_METHODS} ${LIVER_METHOD1} ${FISF_NSP_COL} ${FISF_DICE_COL} ${LIVER_METHOD2} ${FISF_NSP_COL} ${FISF_DICE_COL} ${LIVER_METHOD3} ${RISF_NSP_COL} ${RISF_DICE_COL} ${LIVER_METHOD4} ${RISF_NSP_COL} ${RISF_DICE_COL}

#TODO tmp without ISF MIX
#${EXEC_PY} ${LIVER_BASE}/SIBGRAPI_time_plot.pdf "${NSP_NAME}" ${LIVER_NSP_RANGE} "${TIME_NAME}" ${LIVER_TIME_RANGE} 2 ${LIVER_METHOD1} ${FISF_NSP_COL} ${FISF_TIME_COL} ${LIVER_METHOD3} ${RISF_NSP_COL} ${RISF_FULLTIME_COL}
#${EXEC_PY} ${LIVER_BASE}/SIBGRAPI_br_plot.pdf "${NSP_NAME}" ${LIVER_NSP_RANGE} "${BR_NAME}" ${LIVER_BR_RANGE} ${LIVER_NUM_METHODS} ${LIVER_METHOD1} ${FISF_NSP_COL} ${FISF_BR_COL} ${LIVER_METHOD3} ${RISF_NSP_COL} ${RISF_BR_COL} ${LIVER_METHOD4} ${OTHER_NSP_COL} ${OTHER_BR_COL} ${LIVER_METHOD5} ${OTHER_NSP_COL} ${OTHER_BR_COL} ${LIVER_METHOD6} ${OTHER_NSP_COL} ${OTHER_BR_COL}
#${EXEC_PY} ${LIVER_BASE}/SIBGRAPI_ue_plot.pdf "${NSP_NAME}" ${LIVER_NSP_RANGE} "${UE_NAME}" ${LIVER_UE_RANGE} ${LIVER_NUM_METHODS} ${LIVER_METHOD1} ${FISF_NSP_COL} ${FISF_UE_COL} ${LIVER_METHOD3} ${RISF_NSP_COL} ${RISF_UE_COL} ${LIVER_METHOD4} ${OTHER_NSP_COL} ${OTHER_UE_COL} ${LIVER_METHOD5} ${OTHER_NSP_COL} ${OTHER_UE_COL} ${LIVER_METHOD6} ${OTHER_NSP_COL} ${OTHER_UE_COL}
#${EXEC_PY} ${LIVER_BASE}/SIBGRAPI_dice_plot.pdf "${NSP_NAME}" ${LIVER_NSP_RANGE} "${DICE_NAME}" ${LIVER_DICE_RANGE} ${LIVER_NUM_METHODS} ${LIVER_METHOD1} ${FISF_NSP_COL} ${FISF_DICE_COL} ${LIVER_METHOD3} ${RISF_NSP_COL} ${RISF_DICE_COL} ${LIVER_METHOD4} ${OTHER_NSP_COL} ${OTHER_DICE_COL} ${LIVER_METHOD5} ${OTHER_NSP_COL} ${OTHER_DICE_COL} ${LIVER_METHOD6} ${OTHER_NSP_COL} ${OTHER_DICE_COL}

# Birds Plots
BIRDS_BASE=resultPack/Birds
BIRDS_NSP_RANGE="50 500 0"
BIRDS_TIME_RANGE="0 600 0"
BIRDS_BR_RANGE="0.74 1.00 0" 
BIRDS_UE_RANGE="0.00 0.06 0"
BIRDS_COMP_RANGE="0 0.5 0"
BIRDS_DICE_RANGE="0.8 1.00 0"
BIRDS_NUM_METHODS=4
BIRDS_METHOD1="${BIRDS_BASE}/FISF_MEAN_results.csv ISF-GRID-MEAN 0 1"
BIRDS_METHOD2="${BIRDS_BASE}/FISF_ROOT_results.csv ISF-GRID-ROOT 3 4"
BIRDS_METHOD3="${BIRDS_BASE}/BIRB_GRID_results.csv RISF-GRID 5 2"
BIRDS_METHOD4="${BIRDS_BASE}/RISF_10k_MEAN_GEO_MEAN_results.csv RISF-GEODESIC 2 0"

${EXEC_PY} ${BIRDS_BASE}/SIBGRAPI_time_plot.pdf "${NSP_NAME}" ${BIRDS_NSP_RANGE} "${TIME_NAME}" ${BIRDS_TIME_RANGE} ${BIRDS_NUM_METHODS} ${BIRDS_METHOD1} ${FISF_NSP_COL} ${FISF_TIME_COL} ${BIRDS_METHOD2} ${FISF_NSP_COL} ${FISF_TIME_COL} ${BIRDS_METHOD3} ${RISF_NSP_COL} ${RISF_FULLTIME_COL} ${BIRDS_METHOD4} ${RISF_NSP_COL} ${RISF_FULLTIME_COL}
${EXEC_PY} ${BIRDS_BASE}/SIBGRAPI_br_plot.pdf "${NSP_NAME}" ${BIRDS_NSP_RANGE} "${BR_NAME}" ${BIRDS_BR_RANGE} ${BIRDS_NUM_METHODS} ${BIRDS_METHOD1} ${FISF_NSP_COL} ${FISF_BR_COL} ${BIRDS_METHOD2} ${FISF_NSP_COL} ${FISF_BR_COL} ${BIRDS_METHOD3} ${RISF_NSP_COL} ${RISF_BR_COL} ${BIRDS_METHOD4} ${RISF_NSP_COL} ${RISF_BR_COL}
${EXEC_PY} ${BIRDS_BASE}/SIBGRAPI_ue_plot.pdf "${NSP_NAME}" ${BIRDS_NSP_RANGE} "${UE_NAME}" ${BIRDS_UE_RANGE} ${BIRDS_NUM_METHODS} ${BIRDS_METHOD1} ${FISF_NSP_COL} ${FISF_UE_COL} ${BIRDS_METHOD2} ${FISF_NSP_COL} ${FISF_UE_COL} ${BIRDS_METHOD3} ${RISF_NSP_COL} ${RISF_UE_COL} ${BIRDS_METHOD4} ${RISF_NSP_COL} ${RISF_UE_COL}

