/**
 * @file 
 * @brief Applies post-processing filters on object mask and on its
 * corresponding object membership map, if it exists, as obtained from
 * binary voxel classification.
 * @note It is suitable for the output of codes
 * iftClassifyImageByLogReg.c and iftClassifyImageByOPF.c in
 * ift/demo/Classification, and has been tested for brain
 * segmentation.
 * @author Alexandre Falcao
 * @date Jul 5, 2016
 */

#include "ift.h"

/************************** HEADERS **************************/
iftDict *iftGetArgs(int argc, const char *argv[]);
void iftGetRequiredArgs(  iftDict *args, char **input_mask_path, char **out_mask_path);
void iftValidateRequiredArgs(const char *input_mask_path, const char *out_mask_path);
void iftGetOptionalArgs(  iftDict *args, float *open_radius);
void iftValidateOptionalArgs(float open_radius);
/*************************************************************/

int main(int argc, const char *argv[]) {
    iftDict *args = iftGetArgs(argc, argv);

    // mandatory args
    char *input_mask_path = NULL;
    char *out_mask_path   = NULL;
    // optional args
    float open_radius;

    iftGetRequiredArgs(args, &input_mask_path, &out_mask_path);
    iftGetOptionalArgs(args, &open_radius);

    timer *t1 = iftTic();

    puts("- Reading Input Object Mask");
    iftImage *input_mask = iftReadImageByExt(input_mask_path);
    iftAdjRel *A         = NULL;
    if (iftIs3DImage(input_mask))
      A = iftSpheric(sqrtf(3.0));
    else
      A = iftSpheric(sqrtf(2.0));

    // post-processing
    puts("- Applying Post-Processing");
    puts("  - Open Bin");
    iftImage *aux = iftOpenBin(input_mask,open_radius);
    puts("  - Selecting Largest Component");
    iftImage *output_mask = iftSelectLargestComp(aux,A);
    iftDestroyImage(&aux);
    iftWriteImageByExt(output_mask, out_mask_path);

    char *parent_dir_in = iftParentDir(input_mask_path);
    char *base_out      = iftBasename(out_mask_path);
    const char *ext_in  = iftFileExt(input_mask_path);
    const char *ext_out = iftFileExt(out_mask_path);

    char *filename_in = iftFilename(input_mask_path, ext_in);
    char *regex      = iftConcatStrings(3, filename_in, "_obj_map[0-9]+\\", ext_in);
    iftFileSet *fset = iftLoadFileSetFromDirByRegex(parent_dir_in, regex, true);
    iftFree(parent_dir_in);

    for (size_t i = 0; i < fset->n; i++) {
        iftImage *input_obj_map  = iftReadImageByExt(fset->files[i]->path);
        iftImage *output_obj_map = iftMask(input_obj_map, output_mask);

        // gets the label from the object membership pathname
        char *delin = iftConcatStrings(2, filename_in, "_obj_map");
        char *str   = iftSplitStringAt(fset->files[i]->path, delin, -1);
        char *str2  = iftSplitStringAt(str, iftFileExt(str), 0);
        int label   = atoi(str2);
        iftFree(str);
        iftFree(str2);
        iftFree(delin);

        iftWriteImageByExt(output_obj_map, "%s_obj_map%d%s", base_out, label, ext_out);
        
        iftDestroyImage(&input_obj_map);
        iftDestroyImage(&output_obj_map);
    }

    iftDestroyFileSet(&fset);
    iftFree(filename_in);
    iftFree(regex);
    iftFree(base_out);

    iftDestroyImage(&input_mask);
    iftDestroyImage(&output_mask);
    iftDestroyAdjRel(&A);

    puts("\nDone...");
    puts(iftFormattedTime(iftCompTime(t1, iftToc())));

    return 0;
}



/************************** SOURCES **************************/
iftDict *iftGetArgs(int argc, const char *argv[]) {

    char program_description[2048] = \
        "Applies post-processing filters on the Object Mask, and on its corresponding Object Membership " \
        "Maps (one for each label) if they exist, as obtained from voxel classification.\n" \
        "The Obj Mask and Membership Maps can be generated by the programs:\n" \
        "demo/Classification/iftClassifyImageBy*.c\n\n" \
        "PS: The Obj Membership Map must have the same Obj Mask's Basename with the suffix _obj_mapX, " \
        "where X is the label\n" \
        "Ex: Obj Mask = ~/my_dir/batman.png\n" \
        "Obj Membership Maps: ~/my_dir/batman_obj_map1.png, ~/my_dir/batman_obj_map2.png\n\n" \
        "PS2: The resulting Obj Membership Maps are saved following the same pathname's pattern from the output pathname\n";

    iftCmdLineOpt cmd_line_opts[] = {
        {.short_name = "-i", .long_name = "--input-mask-path", .has_arg=true, .arg_type=IFT_STR_TYPE,
         .required=true, .help="Object mask after voxel classification."},
        {.short_name = "-o", .long_name = "--output-mask-path", .has_arg=true, .arg_type=IFT_STR_TYPE,
         .required=true, .help="Output Post-processed object mask."},
        {.short_name = "-r", .long_name = "--open-radius", .has_arg=true, .arg_type=IFT_DBL_TYPE,
         .required=false, .help="Adjacency radius for opening filter (default 1.0)."},
    };
    int n_opts = sizeof(cmd_line_opts) / sizeof (iftCmdLineOpt);

    // Parser Setup
    iftCmdLineParser *parser = iftCreateCmdLineParser(program_description, n_opts, cmd_line_opts);
    iftDict *args            = iftParseCmdLine(argc, argv, parser); // getting the passed options/arguments
    iftDestroyCmdLineParser(&parser);

    return args;
}



void iftGetRequiredArgs(  iftDict *args, char **input_mask_path, char **out_mask_path){

    *input_mask_path = iftGetStrValFromDict("--input-mask-path", args);
    *out_mask_path   = iftGetStrValFromDict("--output-mask-path", args);

    iftValidateRequiredArgs(*input_mask_path, *out_mask_path);

    puts("-----------------------");
    printf("- Input object mask:  \"%s\"\n", *input_mask_path);
    printf("- Output object mask: \"%s\"\n", *out_mask_path);
    puts("-----------------------");

}

void iftValidateRequiredArgs(const char *input_mask_path, const char *out_mask_path) {
    if (!iftIsImageFile(input_mask_path))
      iftError("Invalid object mask: \"%s\"", "iftValidateRequiredArgs", input_mask_path);

    if (!iftIsImagePathnameValid(out_mask_path)) {
      iftError("Invalid output path: \"%s\"", "iftValidateRequiredArgs", out_mask_path);
    }

    char *parent_dir = iftParentDir(out_mask_path);
    if (!iftDirExists(parent_dir)) {
        iftMakeDir(parent_dir);
    }
    iftFree(parent_dir);
}


void iftGetOptionalArgs(  iftDict *args, float *open_radius) {
  if (iftDictContainKey("--open-radius", args, NULL)) {
    *open_radius = iftGetDblValFromDict("--open-radius", args);
  }
  else *open_radius = 1.0;

  iftValidateOptionalArgs(*open_radius);

  printf("- Adjacency radius for opening filter: %f\n", *open_radius);
  puts("-----------------------\n");

}

void iftValidateOptionalArgs(float open_radius) {
  if (open_radius <= 0.0)
    iftError("Invalid opening radius: %f... Try [1.0]\n", "iftValidateOptionalArgs", open_radius);
}





