name: mo445
channels:
  - defaults
  - pytorch
  - nvidia
  - pytorch3d
  - conda-forge
  - conda
  - iopath
  - huggingface
  - bottler
  - fvcore
dependencies: # Conda packages
  - python=3.12.7
  - pip=24.0
  - wheel=0.43.0
  - setuptools=70.1.1
  - nvidiacub=1.10.0
  - pytorch=2.5.0
  - pytorch-cuda=12.4
  - torchview
  - torchtriton
  - torchvision
  - fvcore
  - iopath 
  - graphviz 
  - imageio 
  - ipython 
  - ipywidgets 
  - joblib 
  - jupyterlab 
  - matplotlib 
  - seaborn 
  - numexpr 
  - numpy 
  - pandas 
  - pillow 
  - psutil 
  - pydot 
  - pyglet 
  - pyopengl 
  - python-graphviz 
  - requests 
  - scikit-image 
  - scikit-learn
  - scipy
  - tqdm
  - widgetsnbextension
  - pydotplus
  - spacy
  - markupsafe
  - black
  - usort
  - flake8
  - pip: # Pip packages
    - random2
    - batchgenerators
    - torch-summary
    - opencv-python
    - torchio
    - torch_snippets