import os, sys


def create_mobio_ift_protocol(mobio_list_path, map_names_path, ift_list_path):
    """Adapt the mobio protocol in the IFT format.
    In the IFT format, the class of the samples is a number from 1 to ... presents in the begining of
    the image filename: e.g: output_dir/000010_image_name.pgm.

    Parameters
    ----------
    mobio_list_path: string
        File to be adapted. E.g: PROTOCOLS/Gender_Independent/mobile0-male/world/train_world.lst

    map_names_path: string
        File that will be used for mapping the original name to the ift name already copyied.
        Each row corresponds to the original filename from the mobio dataset and the file in the ift format.
        The map file was generated by the script convert_mobio_dataset.py

    ift_list_path: string
        Filename of the output file that will store the image filenames in the ift format. 

    Notes
    -----
    Format of the mobio protocols:
    e.g: PROTOCOLS/Gender_Independent/mobile0-male/world/train_world.lst
    'unis/m233/12_mobile/m233_12_f08_i0_0 233\n',
    'unis/m233/12_mobile/m233_12_f09_i0_0 233\n',
    ...

    Format of the map_names: old_filename new_filename
    e.g: map_names.txt -> generated by convert_mobio_dataset.py
    "idiap/m034/02_mobile/m034_02_l11_i0_0 /home/samuka/workspace/bases/mobio/000128_m034_02_l11_i0_0.pgm"
    "uman/m112/07_mobile/m112_07_f19_i0_0 /home/samuka/workspace/bases/mobio/000142_m112_07_f19_i0_0.pgm"

    Format of the IFT format:
    e.g: mobio_ift.neg.train.lst
    "/home/samuka/workspace/bases/mobio/000128_m034_02_l11_i0_0.pgm"
    "/home/samuka/workspace/bases/mobio/000142_m112_07_f19_i0_0.pgm"
    ...
    """
    mobio_list = open(mobio_list_path).readlines()
    mobio_list = [filename.split(" ")[0] for filename in mobio_list]
    mobio_list = list(set(mobio_list)) # delete the duplicate filenames - see the README.txt of the Mobio Protocols.

    print(len(mobio_list))

    map_names_file = open(map_names_path).readlines()
    map_names_file = [filename.split("\n")[0] for filename in map_names_file]
    map_names = {}

    # Build the Map Names from file
    for element in map_names_file:
        old_filename = element.split(" ")[0] 
        new_filename = element.split(" ")[1]
        print("%s\n%s\n" % (old_filename, new_filename))
        map_names[old_filename] = new_filename

    f = open(ift_list_path, "w")

    for old_filename in mobio_list:
        f.write("%s\n" % map_names[old_filename])
    f.close()

    None


def main():
    if len(sys.argv) != 4:
        sys.exit("create_mobio_ift_protocol <mobio_list_path> <map_names_path> <ift_list_path>")

    mobio_list_path = sys.argv[1]
    map_names_path  = sys.argv[2]
    ift_list_path   = sys.argv[3]

    create_mobio_ift_protocol(mobio_list_path, map_names_path, ift_list_path)


if __name__ == "__main__":
    sys.exit(main())