/**
 * @file
 * @brief Visualization of seeds generated by RISF geodesic sampling.
 * @author Felipe Lemes Galvao
 */

#include <ift.h>
#include "iftSuperpixelFeatures.h"
#include "iftExperimentUtility.h"

int main(int argc, char* argv[])
{
  if (argc < 3) {
    printf("Usage: iftTestGeodesicSampling <image> <nSuperpixels> [prev-seg]\n");
    return -1;
  }

  bool isHierarchic = (argc >= 4);

  // Load Image
  iftImage *img = iftReadImageByExt(argv[1]);
  if (iftIs3DImage(img)) {
    printf("Not implemented for 3D images.\n");
    iftDestroyImage(&img);
    return -1;
  }

  // Prepare igraph reference image
  iftImage *refImg = NULL;
  if (isHierarchic) {
    // Load pre-computed superpixel segmentation (previous RISF level)
    refImg = iftReadImageByExt(argv[3]);
  } else {
    // Make superpixel graph act as a pixel-based one
    refImg = iftSelectImageDomain(img->xsize, img->ysize, img->zsize);
    for (int i = 0; i < refImg->n; ++i)
      refImg->val[i] = i + 1;
  }

  // Build igraph
  iftSuperpixelIGraph *igraph = iftInitSuperpixelIGraph(refImg);
  iftAdjRel *A = iftCircular(1.0);
  if (isHierarchic)
    iftSetSuperpixelIGraphExplicitRAG(igraph, A);
  else
    iftSetSuperpixelIGraphImplicitAdjacency(igraph, A);

  // Extract seeds
  int nSuperpixels = atol(argv[2]);
  timer *t1 = iftTic();
  iftSet *seeds = iftRISFGeodesicSampling(igraph, img, nSuperpixels);
  timer *t2 = iftToc();
  printf("Geodesic sampling time = %fs\n", 0.001*iftCompTime(t1,t2));
  //iftMImage *mimg = iftImageToMImage(img, LABNorm_CSPACE);
  //iftSet *seeds = iftRISFGridSampling(igraph, mimg, nSuperpixels);
  //iftDestroyMImage(&mimg);


  // Create visualization showing the seed selection process
  iftColorTable *colorTb = iftCreateColorTable(1, YCbCr_CSPACE);
  int nSeeds = 0;
  for (iftSet *s = seeds; s != NULL; s = s->next) {
    printf("Writing seeds = %d\n", nSeeds+1);
    iftDrawBordersSingleLabel(img, igraph->refImg, s->elem + 1, colorTb->color[0]);
    //for (int p = 0; p < img->n; ++p)
    //  if (igraph->refImg->val[p] - 1 == s->elem)
    //    img->val[p] = 0;
    nSeeds += 1;

    iftWriteImageByExt(img, "geodesic_%03d.png", nSeeds);
  }

  iftDestroyImage(&img);
  iftDestroyImage(&refImg);
  iftDestroySuperpixelIGraph(&igraph);
  iftDestroyAdjRel(&A);
  iftDestroySet(&seeds);

  return 0;
}
