#!/bin/sh
set -x #echo on
set -e #stop on errors

EXEC_PY="python py_scripts/SuperpixelPlot.py"

FISF_NSP_COL=2
FISF_TIME_COL=0
FISF_BR_COL=`expr ${FISF_NSP_COL} + 2`
FISF_UBR_COL=`expr ${FISF_NSP_COL} + 4`
FISF_BP_COL=`expr ${FISF_NSP_COL} + 6`
FISF_UBP_COL=`expr ${FISF_NSP_COL} + 8`
FISF_BF_COL=`expr ${FISF_NSP_COL} + 10`
FISF_UBF_COL=`expr ${FISF_NSP_COL} + 12`
FISF_ASA_COL=`expr ${FISF_NSP_COL} + 14`
FISF_UE_COL=`expr ${FISF_NSP_COL} + 16`
FISF_COMP_COL=`expr ${FISF_NSP_COL} + 18`
FISF_DICE_COL=`expr ${FISF_NSP_COL} + 22`

RISF_NSP_COL=10
RISF_TIME_COL=8
RISF_BR_COL=`expr ${RISF_NSP_COL} + 2`
RISF_UBR_COL=`expr ${RISF_NSP_COL} + 4`
RISF_BP_COL=`expr ${RISF_NSP_COL} + 6`
RISF_UBP_COL=`expr ${RISF_NSP_COL} + 8`
RISF_BF_COL=`expr ${RISF_NSP_COL} + 10`
RISF_UBF_COL=`expr ${RISF_NSP_COL} + 12`
RISF_ASA_COL=`expr ${RISF_NSP_COL} + 14`
RISF_UE_COL=`expr ${RISF_NSP_COL} + 16`
RISF_COMP_COL=`expr ${RISF_NSP_COL} + 18`
RISF_DICE_COL=`expr ${RISF_NSP_COL} + 22`
RISF_FULLTIME_COL=`expr ${RISF_NSP_COL} + 25`
BRAIN_RISF_FULLTIME_COL=`expr ${RISF_NSP_COL} + 31`

OTHER_NSP_COL=1
OTHER_TIME_COL=lul
OTHER_BR_COL=`expr ${OTHER_NSP_COL} + 2`
OTHER_UBR_COL=`expr ${OTHER_NSP_COL} + 4`
OTHER_BP_COL=`expr ${OTHER_NSP_COL} + 6`
OTHER_UBP_COL=`expr ${OTHER_NSP_COL} + 8`
OTHER_BF_COL=`expr ${OTHER_NSP_COL} + 10`
OTHER_UBF_COL=`expr ${OTHER_NSP_COL} + 12`
OTHER_ASA_COL=`expr ${OTHER_NSP_COL} + 14`
OTHER_UE_COL=`expr ${OTHER_NSP_COL} + 16`
OTHER_COMP_COL=`expr ${OTHER_NSP_COL} + 18`
OTHER_DICE_COL=`expr ${OTHER_NSP_COL} + 22`

# General names for axis labels
NSP_NAME="Number of superpixels"
TIME_NAME="Time (ms)"
BR_NAME="Boundary Recall"
UBR_NAME="Groundtruth Union Boundary Recall"
BP_NAME="Boundary Precision"
UBP_NAME="Groundtruth Union Boundary Precision"
BF_NAME="Boundary F-Score"
UBF_NAME="Groundtruth Union Boundary F-Score"
ASA_NAME="Achievable Segmentation Accuracy (ASA)"
UE_NAME="Undersegmentation Error"
COMP_NAME="Compactness"
DICE_NAME="Dice"
DICEAVG_NAME="Average Dice"

# Brain Plots
BRAIN_BASE=resultPack/Brain
BRAIN_NSP_RANGE="500 10000 0"
BRAIN_TIME_RANGE="0 40000 0"
BRAIN_DICE_RANGE="0.80 0.96 0"
BRAIN_DICEOBJ1_RANGE="0.75 0.96 0"
BRAIN_DICEOBJ2_RANGE="0.85 0.97 0"
BRAIN_DICEOBJ3_RANGE="0.85 0.97 0"
BRAIN_NUM_METHODS=3
BRAIN_METHOD1="${BRAIN_BASE}/FISF_results.csv ISF-GRID"
BRAIN_METHOD2="${BRAIN_BASE}/RISF_L1_GRID_results.csv RISF-GRID"
BRAIN_METHOD3="${BRAIN_BASE}/RISF_L1_GEO_results.csv RISF-GEODESIC"

# Brain obj names
BRAIN_DICEOBJ1_NAME="Cerebelum Dice"
BRAIN_DICEOBJ2_NAME="Hemisphere 1 Dice"
BRAIN_DICEOBJ3_NAME="Hemisphere 2 Dice"

${EXEC_PY} ${BRAIN_BASE}/TimePlot.pdf "${NSP_NAME}" ${BRAIN_NSP_RANGE} "${TIME_NAME}" ${BRAIN_TIME_RANGE} ${BRAIN_NUM_METHODS} ${BRAIN_METHOD1} ${FISF_NSP_COL} ${FISF_TIME_COL} ${BRAIN_METHOD2} ${RISF_NSP_COL} ${BRAIN_RISF_FULLTIME_COL} ${BRAIN_METHOD3} ${RISF_NSP_COL} ${BRAIN_RISF_FULLTIME_COL}
${EXEC_PY} ${BRAIN_BASE}/DiceAvgPlot.pdf "${NSP_NAME}" ${BRAIN_NSP_RANGE} "${DICEAVG_NAME}" ${BRAIN_DICE_RANGE} ${BRAIN_NUM_METHODS} ${BRAIN_METHOD1} ${FISF_NSP_COL} ${FISF_DICE_COL} ${BRAIN_METHOD2} ${RISF_NSP_COL} ${RISF_DICE_COL} ${BRAIN_METHOD3} ${RISF_NSP_COL} ${RISF_DICE_COL}
${EXEC_PY} ${BRAIN_BASE}/DiceObj1Plot.pdf "${NSP_NAME}" ${BRAIN_NSP_RANGE} "${BRAIN_DICEOBJ1_NAME}" ${BRAIN_DICEOBJ1_RANGE} ${BRAIN_NUM_METHODS} ${BRAIN_METHOD1} ${FISF_NSP_COL} `expr ${FISF_DICE_COL} + 2` ${BRAIN_METHOD2} ${RISF_NSP_COL} `expr ${RISF_DICE_COL} + 2` ${BRAIN_METHOD3} ${RISF_NSP_COL} `expr ${RISF_DICE_COL} + 2`
${EXEC_PY} ${BRAIN_BASE}/DiceObj2Plot.pdf "${NSP_NAME}" ${BRAIN_NSP_RANGE}  "${BRAIN_DICEOBJ2_NAME}" ${BRAIN_DICEOBJ2_RANGE} ${BRAIN_NUM_METHODS} ${BRAIN_METHOD1} ${FISF_NSP_COL} `expr ${FISF_DICE_COL} + 4` ${BRAIN_METHOD2} ${RISF_NSP_COL} `expr ${RISF_DICE_COL} + 4` ${BRAIN_METHOD3} ${RISF_NSP_COL} `expr ${RISF_DICE_COL} + 4`
${EXEC_PY} ${BRAIN_BASE}/DiceObj3Plot.pdf "${NSP_NAME}" ${BRAIN_NSP_RANGE} "${BRAIN_DICEOBJ3_NAME}" ${BRAIN_DICEOBJ3_RANGE} ${BRAIN_NUM_METHODS} ${BRAIN_METHOD1} ${FISF_NSP_COL} `expr ${FISF_DICE_COL} + 6` ${BRAIN_METHOD2} ${RISF_NSP_COL} `expr ${RISF_DICE_COL} + 6` ${BRAIN_METHOD3} ${RISF_NSP_COL} `expr ${RISF_DICE_COL} + 6`

# Berk Plots
BERK_BASE=resultPack/Berk
BERK_NSP_RANGE="50 500 0"
BERK_TIME_RANGE="0 300 0"
BERK_BR_RANGE="0.6 0.95 0" 
BERK_UBR_RANGE="0.6 0.95 0" 
BERK_BP_RANGE="0.1 0.3 0"
BERK_UBP_RANGE="0.25 0.5 0"
BERK_BF_RANGE="0.2 0.4 0"
BERK_UBF_RANGE="0.38 0.53 0"
BERK_ASA_RANGE="0.87 0.97 0"
BERK_UE_RANGE="0.05 0.28 0"
BERK_COMP_RANGE="0 0.5 0"
BERK_NUM_METHODS=6
BERK_METHOD1="${BERK_BASE}/FISF_MIX_results.csv ISF-MIX-MEAN"
BERK_METHOD2="${BERK_BASE}/FISF_L0_MEAN_5k_05_L1_GEO_results.csv RISF-OPTIMIZED-BR" # TODO UPDATE
BERK_METHOD3="${BERK_BASE}/FISF_L0_MEAN_10k_012_L1_GEO_results.csv RISF-OPTIMIZED-UE" # TODO UPDATE
BERK_METHOD4="${BERK_BASE}/LSC_results.csv LSC"
BERK_METHOD5="${BERK_BASE}/ERGC_results.csv ERGC"
BERK_METHOD6="${BERK_BASE}/SNIC_results.csv SNIC"

# TODO Add time for other methods and switch hardcoded 3 for time plot
${EXEC_PY} ${BERK_BASE}/berk_time_plot.pdf "${NSP_NAME}" ${BERK_NSP_RANGE} "${TIME_NAME}" ${BERK_TIME_RANGE} 3 ${BERK_METHOD1} ${FISF_NSP_COL} ${FISF_TIME_COL} ${BERK_METHOD2} ${RISF_NSP_COL} ${RISF_FULLTIME_COL} ${BERK_METHOD3} ${RISF_NSP_COL} ${RISF_FULLTIME_COL}
${EXEC_PY} ${BERK_BASE}/berk_br_plot.pdf "${NSP_NAME}" ${BERK_NSP_RANGE} "${BR_NAME}" ${BERK_BR_RANGE} ${BERK_NUM_METHODS} ${BERK_METHOD1} ${FISF_NSP_COL} ${FISF_BR_COL} ${BERK_METHOD2} ${RISF_NSP_COL} ${RISF_BR_COL} ${BERK_METHOD3} ${RISF_NSP_COL} ${RISF_BR_COL} ${BERK_METHOD4} ${OTHER_NSP_COL} ${OTHER_BR_COL} ${BERK_METHOD5} ${OTHER_NSP_COL} ${OTHER_BR_COL} ${BERK_METHOD6} ${OTHER_NSP_COL} ${OTHER_BR_COL}
${EXEC_PY} ${BERK_BASE}/berk_ubr_plot.pdf "${NSP_NAME}" ${BERK_NSP_RANGE} "${UBR_NAME}" ${BERK_UBR_RANGE} ${BERK_NUM_METHODS} ${BERK_METHOD1} ${FISF_NSP_COL} ${FISF_UBR_COL} ${BERK_METHOD2} ${RISF_NSP_COL} ${RISF_UBR_COL} ${BERK_METHOD3} ${RISF_NSP_COL} ${RISF_UBR_COL} ${BERK_METHOD4} ${OTHER_NSP_COL} ${OTHER_UBR_COL} ${BERK_METHOD5} ${OTHER_NSP_COL} ${OTHER_UBR_COL} ${BERK_METHOD6} ${OTHER_NSP_COL} ${OTHER_UBR_COL}
${EXEC_PY} ${BERK_BASE}/berk_bp_plot.pdf "${NSP_NAME}" ${BERK_NSP_RANGE} "${BP_NAME}" ${BERK_BP_RANGE} ${BERK_NUM_METHODS} ${BERK_METHOD1} ${FISF_NSP_COL} ${FISF_BP_COL} ${BERK_METHOD2} ${RISF_NSP_COL} ${RISF_BP_COL} ${BERK_METHOD3} ${RISF_NSP_COL} ${RISF_BP_COL} ${BERK_METHOD4} ${OTHER_NSP_COL} ${OTHER_BP_COL} ${BERK_METHOD5} ${OTHER_NSP_COL} ${OTHER_BP_COL} ${BERK_METHOD6} ${OTHER_NSP_COL} ${OTHER_BP_COL}
${EXEC_PY} ${BERK_BASE}/berk_ubp_plot.pdf "${NSP_NAME}" ${BERK_NSP_RANGE} "${UBP_NAME}" ${BERK_UBP_RANGE} ${BERK_NUM_METHODS} ${BERK_METHOD1} ${FISF_NSP_COL} ${FISF_UBP_COL} ${BERK_METHOD2} ${RISF_NSP_COL} ${RISF_UBP_COL} ${BERK_METHOD3} ${RISF_NSP_COL} ${RISF_UBP_COL} ${BERK_METHOD4} ${OTHER_NSP_COL} ${OTHER_UBP_COL} ${BERK_METHOD5} ${OTHER_NSP_COL} ${OTHER_UBP_COL} ${BERK_METHOD6} ${OTHER_NSP_COL} ${OTHER_UBP_COL}
${EXEC_PY} ${BERK_BASE}/berk_bf_plot.pdf "${NSP_NAME}" ${BERK_NSP_RANGE} "${BF_NAME}" ${BERK_BF_RANGE} ${BERK_NUM_METHODS} ${BERK_METHOD1} ${FISF_NSP_COL} ${FISF_BF_COL} ${BERK_METHOD2} ${RISF_NSP_COL} ${RISF_BF_COL} ${BERK_METHOD3} ${RISF_NSP_COL} ${RISF_BF_COL} ${BERK_METHOD4} ${OTHER_NSP_COL} ${OTHER_BF_COL} ${BERK_METHOD5} ${OTHER_NSP_COL} ${OTHER_BF_COL} ${BERK_METHOD6} ${OTHER_NSP_COL} ${OTHER_BF_COL}
${EXEC_PY} ${BERK_BASE}/berk_ubf_plot.pdf "${NSP_NAME}" ${BERK_NSP_RANGE} "${UBF_NAME}" ${BERK_UBF_RANGE} ${BERK_NUM_METHODS} ${BERK_METHOD1} ${FISF_NSP_COL} ${FISF_UBF_COL} ${BERK_METHOD2} ${RISF_NSP_COL} ${RISF_UBF_COL} ${BERK_METHOD3} ${RISF_NSP_COL} ${RISF_UBF_COL} ${BERK_METHOD4} ${OTHER_NSP_COL} ${OTHER_UBF_COL} ${BERK_METHOD5} ${OTHER_NSP_COL} ${OTHER_UBF_COL} ${BERK_METHOD6} ${OTHER_NSP_COL} ${OTHER_UBF_COL}
${EXEC_PY} ${BERK_BASE}/berk_brXbp_plot.pdf "${BR_NAME}" ${BERK_BR_RANGE} "${BP_NAME}" ${BERK_BP_RANGE} ${BERK_NUM_METHODS} ${BERK_METHOD1} ${FISF_BR_COL} ${FISF_BP_COL} ${BERK_METHOD2} ${RISF_BR_COL} ${RISF_BP_COL} ${BERK_METHOD3} ${RISF_BR_COL} ${RISF_BP_COL} ${BERK_METHOD4} ${OTHER_BR_COL} ${OTHER_BP_COL} ${BERK_METHOD5} ${OTHER_BR_COL} ${OTHER_BP_COL} ${BERK_METHOD6} ${OTHER_BR_COL} ${OTHER_BP_COL}
${EXEC_PY} ${BERK_BASE}/berk_ubrXubp_plot.pdf "${UBR_NAME}" ${BERK_UBR_RANGE} "${UBP_NAME}" ${BERK_UBP_RANGE} ${BERK_NUM_METHODS} ${BERK_METHOD1} ${FISF_UBR_COL} ${FISF_UBP_COL} ${BERK_METHOD2} ${RISF_UBR_COL} ${RISF_UBP_COL} ${BERK_METHOD3} ${RISF_UBR_COL} ${RISF_UBP_COL} ${BERK_METHOD4} ${OTHER_UBR_COL} ${OTHER_UBP_COL} ${BERK_METHOD5} ${OTHER_UBR_COL} ${OTHER_UBP_COL} ${BERK_METHOD6} ${OTHER_UBR_COL} ${OTHER_UBP_COL}
${EXEC_PY} ${BERK_BASE}/berk_asa_plot.pdf "${NSP_NAME}" ${BERK_NSP_RANGE} "${ASA_NAME}" ${BERK_ASA_RANGE} ${BERK_NUM_METHODS} ${BERK_METHOD1} ${FISF_NSP_COL} ${FISF_ASA_COL} ${BERK_METHOD2} ${RISF_NSP_COL} ${RISF_ASA_COL} ${BERK_METHOD3} ${RISF_NSP_COL} ${RISF_ASA_COL} ${BERK_METHOD4} ${OTHER_NSP_COL} ${OTHER_ASA_COL} ${BERK_METHOD5} ${OTHER_NSP_COL} ${OTHER_ASA_COL} ${BERK_METHOD6} ${OTHER_NSP_COL} ${OTHER_ASA_COL}
${EXEC_PY} ${BERK_BASE}/berk_ue_plot.pdf "${NSP_NAME}" ${BERK_NSP_RANGE} "${UE_NAME}" ${BERK_UE_RANGE} ${BERK_NUM_METHODS} ${BERK_METHOD1} ${FISF_NSP_COL} ${FISF_UE_COL} ${BERK_METHOD2} ${RISF_NSP_COL} ${RISF_UE_COL} ${BERK_METHOD3} ${RISF_NSP_COL} ${RISF_UE_COL} ${BERK_METHOD4} ${OTHER_NSP_COL} ${OTHER_UE_COL} ${BERK_METHOD5} ${OTHER_NSP_COL} ${OTHER_UE_COL} ${BERK_METHOD6} ${OTHER_NSP_COL} ${OTHER_UE_COL}
${EXEC_PY} ${BERK_BASE}/berk_comp_plot.pdf "${NSP_NAME}" ${BERK_NSP_RANGE} "${COMP_NAME}" ${BERK_COMP_RANGE} ${BERK_NUM_METHODS} ${BERK_METHOD1} ${FISF_NSP_COL} ${FISF_COMP_COL} ${BERK_METHOD2} ${RISF_NSP_COL} ${RISF_COMP_COL} ${BERK_METHOD3} ${RISF_NSP_COL} ${RISF_COMP_COL} ${BERK_METHOD4} ${OTHER_NSP_COL} ${OTHER_COMP_COL} ${BERK_METHOD5} ${OTHER_NSP_COL} ${OTHER_COMP_COL} ${BERK_METHOD6} ${OTHER_NSP_COL} ${OTHER_COMP_COL}

# Berk comparison of RISF methods
BERK_RISF_NUM_METHODS=6
BERK_RISF1="${BERK_BASE}/FISF_L0_MEAN_5k_012_L1_GEO_results.csv ISF-MEAN-5k-012"
BERK_RISF2="${BERK_BASE}/FISF_L0_MEAN_5k_02_L1_GEO_results.csv ISF-MEAN-5k-02"
BERK_RISF3="${BERK_BASE}/FISF_L0_MEAN_5k_05_L1_GEO_results.csv ISF-MEAN-5k-05"
BERK_RISF4="${BERK_BASE}/FISF_L0_MEAN_10k_012_L1_GEO_results.csv ISF-MEAN-10k-012"
BERK_RISF5="${BERK_BASE}/FISF_L0_MEAN_10k_02_L1_GEO_results.csv ISF-MEAN-10k-02"
BERK_RISF6="${BERK_BASE}/FISF_L0_MEAN_10k_05_L1_GEO_results.csv ISF-MEAN-10k-05"

${EXEC_PY} ${BERK_BASE}/RISF_br_plot.pdf "${NSP_NAME}" ${BERK_NSP_RANGE} "${BR_NAME}" ${BERK_BR_RANGE} ${BERK_RISF_NUM_METHODS} ${BERK_RISF1} ${RISF_NSP_COL} ${RISF_BR_COL} ${BERK_RISF2} ${RISF_NSP_COL} ${RISF_BR_COL} ${BERK_RISF3} ${RISF_NSP_COL} ${RISF_BR_COL} ${BERK_RISF4} ${RISF_NSP_COL} ${RISF_BR_COL} ${BERK_RISF5} ${RISF_NSP_COL} ${RISF_BR_COL} ${BERK_RISF6} ${RISF_NSP_COL} ${RISF_BR_COL}
${EXEC_PY} ${BERK_BASE}/RISF_ue_plot.pdf "${NSP_NAME}" ${BERK_NSP_RANGE} "${UE_NAME}" ${BERK_UE_RANGE} ${BERK_RISF_NUM_METHODS} ${BERK_RISF1} ${RISF_NSP_COL} ${RISF_UE_COL} ${BERK_RISF2} ${RISF_NSP_COL} ${RISF_UE_COL} ${BERK_RISF3} ${RISF_NSP_COL} ${RISF_UE_COL} ${BERK_RISF4} ${RISF_NSP_COL} ${RISF_UE_COL} ${BERK_RISF5} ${RISF_NSP_COL} ${RISF_UE_COL} ${BERK_RISF6} ${RISF_NSP_COL} ${RISF_UE_COL}
${EXEC_PY} ${BERK_BASE}/RISF_asa_plot.pdf "${NSP_NAME}" ${BERK_NSP_RANGE} "${ASA_NAME}" ${BERK_ASA_RANGE} ${BERK_RISF_NUM_METHODS} ${BERK_RISF1} ${RISF_NSP_COL} ${RISF_ASA_COL} ${BERK_RISF2} ${RISF_NSP_COL} ${RISF_ASA_COL} ${BERK_RISF3} ${RISF_NSP_COL} ${RISF_ASA_COL} ${BERK_RISF4} ${RISF_NSP_COL} ${RISF_ASA_COL} ${BERK_RISF5} ${RISF_NSP_COL} ${RISF_ASA_COL} ${BERK_RISF6} ${RISF_NSP_COL} ${RISF_ASA_COL}
${EXEC_PY} ${BERK_BASE}/RISF_comp_plot.pdf "${NSP_NAME}" ${BERK_NSP_RANGE} "${COMP_NAME}" ${BERK_COMP_RANGE} ${BERK_RISF_NUM_METHODS} ${BERK_RISF1} ${RISF_NSP_COL} ${RISF_COMP_COL} ${BERK_RISF2} ${RISF_NSP_COL} ${RISF_COMP_COL} ${BERK_RISF3} ${RISF_NSP_COL} ${RISF_COMP_COL} ${BERK_RISF4} ${RISF_NSP_COL} ${RISF_COMP_COL} ${BERK_RISF5} ${RISF_NSP_COL} ${RISF_COMP_COL} ${BERK_RISF6} ${RISF_NSP_COL} ${RISF_COMP_COL}

# Berk ISF vs RISF comparison
BERK_ISF_NUM_METHODS=5
BERK_ISF1="${BERK_BASE}/FISF_GRID_results.csv ISF-GRID"
BERK_ISF2="${BERK_BASE}/FISF_MIX_results.csv ISF-MIX"
BERK_ISF3="${BERK_BASE}/FISF_L0_MEAN_10k_05_L1_GRID_05_results.csv FISF05-to-RISF-GRID05"
BERK_ISF4="${BERK_BASE}/FISF_L0_MEAN_10k_012_L1_GRID_05_results.csv FISF012-to-RISF-GRID05"
BERK_ISF5="${BERK_BASE}/FISF_L0_MEAN_10k_012_L1_GEO_results.csv RISF-GEO"

${EXEC_PY} ${BERK_BASE}/ISFvsRISF_br_plot.pdf "${NSP_NAME}" ${BERK_NSP_RANGE} "${BR_NAME}" ${BERK_BR_RANGE} ${BERK_ISF_NUM_METHODS} ${BERK_ISF1} ${FISF_NSP_COL} ${FISF_BR_COL} ${BERK_ISF2} ${FISF_NSP_COL} ${FISF_BR_COL} ${BERK_ISF3} ${RISF_NSP_COL} ${RISF_BR_COL} ${BERK_ISF4} ${RISF_NSP_COL} ${RISF_BR_COL} ${BERK_ISF5} ${RISF_NSP_COL} ${RISF_BR_COL}
${EXEC_PY} ${BERK_BASE}/ISFvsRISF_ue_plot.pdf "${NSP_NAME}" ${BERK_NSP_RANGE} "${UE_NAME}" ${BERK_UE_RANGE} ${BERK_ISF_NUM_METHODS} ${BERK_ISF1} ${FISF_NSP_COL} ${FISF_UE_COL} ${BERK_ISF2} ${FISF_NSP_COL} ${FISF_UE_COL} ${BERK_ISF3} ${RISF_NSP_COL} ${RISF_UE_COL} ${BERK_ISF4} ${RISF_NSP_COL} ${RISF_UE_COL} ${BERK_ISF5} ${RISF_NSP_COL} ${RISF_UE_COL}
${EXEC_PY} ${BERK_BASE}/ISFvsRISF_time_plot.pdf "${NSP_NAME}" ${BERK_NSP_RANGE} "${TIME_NAME}" ${BERK_TIME_RANGE} ${BERK_ISF_NUM_METHODS} ${BERK_ISF1} ${FISF_NSP_COL} ${FISF_TIME_COL} ${BERK_ISF2} ${FISF_NSP_COL} ${FISF_TIME_COL} ${BERK_ISF3} ${RISF_NSP_COL} ${RISF_FULLTIME_COL} ${BERK_ISF4} ${RISF_NSP_COL} ${RISF_FULLTIME_COL} ${BERK_ISF5} ${RISF_NSP_COL} ${RISF_FULLTIME_COL}

# Liver Plots
LIVER_BASE=resultPack/Liver
LIVER_NSP_RANGE="50 500 0"
LIVER_TIME_RANGE="0 500 0"
LIVER_BR_RANGE="0.69 1.00 0" 
LIVER_UE_RANGE="0.00 0.06 0"
LIVER_COMP_RANGE="0 0.6 0"
LIVER_ASA_RANGE="0.97 1.0 0"
LIVER_DICE_RANGE="0.92 0.99 0"
LIVER_NUM_METHODS=6
LIVER_METHOD1="${LIVER_BASE}/FISF_32_results.csv ISF"
LIVER_METHOD2="${LIVER_BASE}/L0_5000_32_L1_GEO_32_results.csv RISF-5k-GEO" # TODO UPDATE
LIVER_METHOD3="${LIVER_BASE}/L0_10000_32_L1_GEO_32_results.csv RISF-10k-GEO" # TODO UPDATE
LIVER_METHOD4="${LIVER_BASE}/LSC_results.csv LSC"
LIVER_METHOD5="${LIVER_BASE}/ERGC_results.csv ERGC"
LIVER_METHOD6="${LIVER_BASE}/SNIC_results.csv SNIC"

# TODO Add time for other methods and switch hardcoded 3 for time plot
${EXEC_PY} ${LIVER_BASE}/liver_time_plot.pdf "${NSP_NAME}" ${LIVER_NSP_RANGE} "${TIME_NAME}" ${LIVER_TIME_RANGE} 3 ${LIVER_METHOD1} ${FISF_NSP_COL} ${FISF_TIME_COL} ${LIVER_METHOD2} ${RISF_NSP_COL} ${RISF_FULLTIME_COL} ${LIVER_METHOD3} ${RISF_NSP_COL} ${RISF_FULLTIME_COL}
${EXEC_PY} ${LIVER_BASE}/liver_br_plot.pdf "${NSP_NAME}" ${LIVER_NSP_RANGE} "${BR_NAME}" ${LIVER_BR_RANGE} ${LIVER_NUM_METHODS} ${LIVER_METHOD1} ${FISF_NSP_COL} ${FISF_BR_COL} ${LIVER_METHOD2} ${RISF_NSP_COL} ${RISF_BR_COL} ${LIVER_METHOD3} ${RISF_NSP_COL} ${RISF_BR_COL} ${LIVER_METHOD4} ${OTHER_NSP_COL} ${OTHER_BR_COL} ${LIVER_METHOD5} ${OTHER_NSP_COL} ${OTHER_BR_COL} ${LIVER_METHOD6} ${OTHER_NSP_COL} ${OTHER_BR_COL}
${EXEC_PY} ${LIVER_BASE}/liver_ue_plot.pdf "${NSP_NAME}" ${LIVER_NSP_RANGE} "${UE_NAME}" ${LIVER_UE_RANGE} ${LIVER_NUM_METHODS} ${LIVER_METHOD1} ${FISF_NSP_COL} ${FISF_UE_COL} ${LIVER_METHOD2} ${RISF_NSP_COL} ${RISF_UE_COL} ${LIVER_METHOD3} ${RISF_NSP_COL} ${RISF_UE_COL} ${LIVER_METHOD4} ${OTHER_NSP_COL} ${OTHER_UE_COL} ${LIVER_METHOD5} ${OTHER_NSP_COL} ${OTHER_UE_COL} ${LIVER_METHOD6} ${OTHER_NSP_COL} ${OTHER_UE_COL}
${EXEC_PY} ${LIVER_BASE}/liver_comp_plot.pdf "${NSP_NAME}" ${LIVER_NSP_RANGE} "${COMP_NAME}" ${LIVER_COMP_RANGE} ${LIVER_NUM_METHODS} ${LIVER_METHOD1} ${FISF_NSP_COL} ${FISF_COMP_COL} ${LIVER_METHOD2} ${RISF_NSP_COL} ${RISF_COMP_COL} ${LIVER_METHOD3} ${RISF_NSP_COL} ${RISF_COMP_COL} ${LIVER_METHOD4} ${OTHER_NSP_COL} ${OTHER_COMP_COL} ${LIVER_METHOD5} ${OTHER_NSP_COL} ${OTHER_COMP_COL} ${LIVER_METHOD6} ${OTHER_NSP_COL} ${OTHER_COMP_COL}
${EXEC_PY} ${LIVER_BASE}/liver_asa_plot.pdf "${NSP_NAME}" ${LIVER_NSP_RANGE} "${ASA_NAME}" ${LIVER_ASA_RANGE} ${LIVER_NUM_METHODS} ${LIVER_METHOD1} ${FISF_NSP_COL} ${FISF_ASA_COL} ${LIVER_METHOD2} ${RISF_NSP_COL} ${RISF_ASA_COL} ${LIVER_METHOD3} ${RISF_NSP_COL} ${RISF_ASA_COL} ${LIVER_METHOD4} ${OTHER_NSP_COL} ${OTHER_ASA_COL} ${LIVER_METHOD5} ${OTHER_NSP_COL} ${OTHER_ASA_COL} ${LIVER_METHOD6} ${OTHER_NSP_COL} ${OTHER_ASA_COL}
${EXEC_PY} ${LIVER_BASE}/liver_dice_plot.pdf "${NSP_NAME}" ${LIVER_NSP_RANGE} "${DICE_NAME}" ${LIVER_DICE_RANGE} ${LIVER_NUM_METHODS} ${LIVER_METHOD1} ${FISF_NSP_COL} ${FISF_DICE_COL} ${LIVER_METHOD2} ${RISF_NSP_COL} ${RISF_DICE_COL} ${LIVER_METHOD3} ${RISF_NSP_COL} ${RISF_DICE_COL} ${LIVER_METHOD4} ${OTHER_NSP_COL} ${OTHER_DICE_COL} ${LIVER_METHOD5} ${OTHER_NSP_COL} ${OTHER_DICE_COL} ${LIVER_METHOD6} ${OTHER_NSP_COL} ${OTHER_DICE_COL}

# Birds Plots
BIRDS_BASE=resultPack/Birds
BIRDS_NSP_RANGE="50 500 0"
BIRDS_TIME_RANGE="0 600 0"
BIRDS_BR_RANGE="0.74 1.00 0" 
BIRDS_UE_RANGE="0.00 0.06 0"
BIRDS_COMP_RANGE="0 0.5 0"
BIRDS_DICE_RANGE="0.8 1.00 0"
BIRDS_NUM_METHODS=6
BIRDS_METHOD1="${BIRDS_BASE}/FISF_ROOT_results.csv ISF-GRID-ROOT"
BIRDS_METHOD2="${BIRDS_BASE}/RISF_10k_MEAN_GEO_ROOT_results.csv RISF-GEO-ROOT" # TODO UPDATE
BIRDS_METHOD3="${BIRDS_BASE}/RISF_10k_MEAN_GEO_MEAN_results.csv RISF-GEO-MEAN" # TODO UPDATE
BIRDS_METHOD4="${BIRDS_BASE}/LSC_results.csv LSC"
BIRDS_METHOD5="${BIRDS_BASE}/ERGC_results.csv ERGC"
BIRDS_METHOD6="${BIRDS_BASE}/SNIC_results.csv SNIC"

# TODO Add time for other methods and switch hardcoded 3 for time plot
${EXEC_PY} ${BIRDS_BASE}/birds_time_plot.pdf "${NSP_NAME}" ${BIRDS_NSP_RANGE} "${TIME_NAME}" ${BIRDS_TIME_RANGE} 3 ${BIRDS_METHOD1} ${FISF_NSP_COL} ${FISF_TIME_COL} ${BIRDS_METHOD2} ${RISF_NSP_COL} ${RISF_FULLTIME_COL} ${BIRDS_METHOD3} ${RISF_NSP_COL} ${RISF_FULLTIME_COL}
${EXEC_PY} ${BIRDS_BASE}/birds_br_plot.pdf "${NSP_NAME}" ${BIRDS_NSP_RANGE} "${BR_NAME}" ${BIRDS_BR_RANGE} ${BIRDS_NUM_METHODS} ${BIRDS_METHOD1} ${FISF_NSP_COL} ${FISF_BR_COL} ${BIRDS_METHOD2} ${RISF_NSP_COL} ${RISF_BR_COL} ${BIRDS_METHOD3} ${RISF_NSP_COL} ${RISF_BR_COL} ${BIRDS_METHOD4} ${OTHER_NSP_COL} ${OTHER_BR_COL} ${BIRDS_METHOD5} ${OTHER_NSP_COL} ${OTHER_BR_COL} ${BIRDS_METHOD6} ${OTHER_NSP_COL} ${OTHER_BR_COL}
${EXEC_PY} ${BIRDS_BASE}/birds_ue_plot.pdf "${NSP_NAME}" ${BIRDS_NSP_RANGE} "${UE_NAME}" ${BIRDS_UE_RANGE} ${BIRDS_NUM_METHODS} ${BIRDS_METHOD1} ${FISF_NSP_COL} ${FISF_UE_COL} ${BIRDS_METHOD2} ${RISF_NSP_COL} ${RISF_UE_COL} ${BIRDS_METHOD3} ${RISF_NSP_COL} ${RISF_UE_COL} ${BIRDS_METHOD4} ${OTHER_NSP_COL} ${OTHER_UE_COL} ${BIRDS_METHOD5} ${OTHER_NSP_COL} ${OTHER_UE_COL} ${BIRDS_METHOD6} ${OTHER_NSP_COL} ${OTHER_UE_COL}
${EXEC_PY} ${BIRDS_BASE}/birds_comp_plot.pdf "${NSP_NAME}" ${BIRDS_NSP_RANGE} "${COMP_NAME}" ${BIRDS_COMP_RANGE} ${BIRDS_NUM_METHODS} ${BIRDS_METHOD1} ${FISF_NSP_COL} ${FISF_COMP_COL} ${BIRDS_METHOD2} ${RISF_NSP_COL} ${RISF_COMP_COL} ${BIRDS_METHOD3} ${RISF_NSP_COL} ${RISF_COMP_COL} ${BIRDS_METHOD4} ${OTHER_NSP_COL} ${OTHER_COMP_COL} ${BIRDS_METHOD5} ${OTHER_NSP_COL} ${OTHER_COMP_COL} ${BIRDS_METHOD6} ${OTHER_NSP_COL} ${OTHER_COMP_COL}
${EXEC_PY} ${BIRDS_BASE}/birds_dice_plot.pdf "${NSP_NAME}" ${BIRDS_NSP_RANGE} "${DICE_NAME}" ${BIRDS_DICE_RANGE} ${BIRDS_NUM_METHODS} ${BIRDS_METHOD1} ${FISF_NSP_COL} ${FISF_DICE_COL} ${BIRDS_METHOD2} ${RISF_NSP_COL} ${RISF_DICE_COL} ${BIRDS_METHOD3} ${RISF_NSP_COL} ${RISF_DICE_COL} ${BIRDS_METHOD4} ${OTHER_NSP_COL} ${OTHER_DICE_COL} ${BIRDS_METHOD5} ${OTHER_NSP_COL} ${OTHER_DICE_COL} ${BIRDS_METHOD6} ${OTHER_NSP_COL} ${OTHER_DICE_COL}

